@loadOrder =
  FILES: {}
  FULL_NAME: 'buom01:load-order'
  SHORT_NAME: 'load-order'
  CONFIG_FULL_NAME: 'buom01:load-order-config'
  CONFIG_SHORT_NAME: 'load-order-config'
  CONFIG_PATH: 'packages/load-order-config'
  CONFIG_VERSION: '0.2.0'
  VARIABLE_NAME: 'loadOrder'
